services:
  - type: web
    name: keycloak
    env: docker
    healthCheckPath: /status
    autoDeploy: false
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: etopo-kc-db
          property: database
      - key: DB_PASSWORD
        fromDatabase:
          name: etopo-kc-db
          property: password
      - key: DB_USER
        fromDatabase:
          name: etopo-kc-db
          property: user
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: etopo-kc-db
          property: connectionString

databases:
  - name: goatcounter-postgres
    databaseName: goatcounter
    user: goatcounter
